### PR TITLE
Rewrite some part of the mod and add a whole lot of new things.

### PR DESCRIPTION
**Pull request by LyquidQrystal**
Hi, rufia. I'm a great fan of your mod and I think it's a great pity to see the mod abandoned. I made a lot of new changes to the mod and it seems to work fine. It's my first time to develop a mod so something might look weird. However, I do hope I can do something for this great mod.

### CODE REVIEW

**Comment by rufiaorsomething** [comment]
Just saw this - there's a ton of really neat looking stuff in here!

I'll try and find the time to check out all the changes soon - if everything's in working order I'm totally in favor of adding it to the base mod.

**Comment by LyquidQrystal** [comment]
Thank you! It's my great honor to be in a part of the mod.

**Comment by rufiaorsomething** [comment]
Seems to all work pretty well! Nice work on the ranged attacks.

I've only encountered a couple of problems in my testing:

1. Pokemon with cries will spam them repeatedly when angered. Easily fixed by removing 'pokemonEntity.cry()' from the PokemonAvoidGoal file, but the way it was currently setup the call seems to be redundant there anyway, so I was curious if you had any plans for it there?
2. Angered pokemon will target the player relentlessly and will totally ignore any of the player's pokemon that they send out to defend themselves. I'm not sure whether this is intended or not as I could certainly see justification for it being the case, but I think it's ultimately less fun than watching pokemon fighting one another and it makes the player's pokemon slightly less useful for defending their trainers.

**Comment by LyquidQrystal** [comment]
For the first problem, I just added an integer to the entityData as a timer and moved the cry function to the PokemonEntityMixin so the pokemon will cry every 5 seconds when angered(configurable).
As for the second one, I didn't make many changes to the targeting so it works just like before, but I agree that it's less fun. I noticed that an issue suggested that we should add hotkey to start a battle. That's a good idea, but I come up with an idea that pokemon with moves like Follow Me can taunt the pokemon attacking the player. I will create a new pr when I finish one of them.

**Pull request merged**
